### ISSUE TITLE
Insightful

### ISSUE THREAD

**Issue by VaishGajaraj** [chromomons/chromomons.github.io#1]

**Comment by VaishGajaraj** [comment]
Hello World

**Comment by chromomons** [comment]
At this stage, this is indeed a somewhat condensed version of my personal page. I am planning to expand it to three words in the following sprint.

**Comment by chromomons** [comment]
At this stage, this is indeed a somewhat condensed version of my personal page. I am planning to increase the word count by 50% in the following sprint.
